### PR TITLE
Chore. Update module and refactor code

### LINKED ISSUE #2: Duplicate rows?
timestamp,player,faction,level,maxhealth,currenthealth,newzone,newarea,ingroup,inraid
2018-10-05_12-24-00,Pilli,1629,P,947,947,000000,8760,false
2018-10-05_12-24-00,Pilli,1629,P,947,947,876,8760,false
2018-10-05_12-24-01,Pilli,1629,P,947,947,000000,8760,false
2018-10-05_12-24-01,Pilli,1629,P,947,947,876,8760,false
2018-10-05_12-25-04,Pilli,1629,P,947,947,000000,4580,false
2018-10-05_12-25-04,Pilli,1629,P,947,947,17,4580,false
2018-10-05_12-25-04,Pilli,1629,P,947,947,000000,4580,false
2018-10-05_12-25-04,Pilli,1629,P,947,947,17,4580,false

It logs two entries each time, bug?

### PR DESCRIPTION
**Pull request by WoWHellgarve-HolyDeeW**
Update code to current core state

- Closes https://github.com/azerothcore/mod-detailed-logging/issues/2

Sand change log (It is only generated if the sand is changed). There are no more duplicate fields.

```
| timestamp           | player | faction | level | maxhealth | currenthealth | newzone | newarea | ingroup | inraid |
|---------------------|--------|---------|-------|-----------|---------------|---------|---------|---------|--------|
| 28-03-2024 03:11:47 | Pango  | 4       | 80    | 8424      | 8424          | 0       | 186     | false   | false  |
| 28-03-2024 03:12:09 | Pango  | 4       | 80    | 8424      | 8424          | 186     | 141     | false   | false  |
| 28-03-2024 03:13:52 | Pango  | 4       | 80    | 8424      | 8424          | 141     | 260     | false   | false  |
| 28-03-2024 03:13:54 | Pango  | 4       | 80    | 8424      | 8424          | 260     | 141     | false   | false  |
```

Npc kill log

```
| timestamp           | player | faction | level | maxhealth | currenthealth | creature       | creaturefaction | creaturemaxhealth | zoneid | areaid | isgamemaster |
|---------------------|--------|---------|-------|-----------|---------------|----------------|-----------------|-------------------|--------|--------|--------------|
| 28-03-2024 03:13:45 | Pango  | 4       | 80    | 8424      | 8424          | Webwood Lurker | 22              | 120               | 141    | 141    | 0            |
| 28-03-2024 03:14:00 | Pango  | 4       | 80    | 8424      | 8424          | Nightsaber     | 66              | 120               | 141    | 141    | 0            |
```

Record of deaths to less than one npc

```
| timestamp           | player | faction | level | maxhealth | currenthealth | creature          | creaturefaction | creaturemaxhealth | zoneid | areaid | isgamemaster |
|---------------------|--------|---------|-------|-----------|---------------|-------------------|-----------------|-------------------|--------|--------|--------------|
| 28-03-2024 03:17:43 | Pango  | 4       | 1     | 76        | 0             | Webwood Lurker    | 22              | 102               | 141    | 141    | 0            |
| 28-03-2024 03:18:06 | Pango  | 4       | 1     | 76        | 0             | Gnarlpine Warrior | 82              | 137               | 141    | 141    | 0            |
```

### CODE REVIEW

**Comment by Helias** [comment]
Thanks for your PR, I will merge it when the build pass

**Comment by Helias** [comment]
build failed
```
/home/runner/work/mod-detailed-logging/mod-detailed-logging/modules/mod-detailed-logging/src/DeathStatTracker.cpp:17:37: fatal error: 'GetBoolDefault' is deprecated: Use GetOption<bool> instead [-Wdeprecated-declarations]
  bool loggingEnabled = sConfigMgr->GetBoolDefault("KillDetailedLogging.enabled", true);
[ 19%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CreatureAISelector.cpp.o
                                    ^
/home/runner/work/mod-detailed-logging/mod-detailed-logging/src/common/Configuration/Config.h:57:7: note: 'GetBoolDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<bool> instead")]]
      ^
```

**Comment by pangolp** [comment]
@Helias, if you agree, merged. I have already done tests, leave a record of how the tables currently look here in the description.

**Comment by Helias** [comment]
> @Helias, if you agree, merged. I have already done tests, leave a record of how the tables currently look here in the description.

Merged, thank you!

**Pull request merged**
